[package]
name = "bot-hohmach-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "model", "rustls_backend"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }

